-- return {
-- --   {'akinsho/toggleterm.nvim', version = "*", config = true}
--   -- 'akinsho/toggleterm.nvim',
--   -- version = "*",
--   -- config = function()
--   --   require('toggleterm').setup{
--   --     open_mapping = "\\"
--   --     
--   --     pj
--   --   }
--   -- end
--   'akinsho/toggleterm.nvim',
--   version = "",
--   opts = {
--     open_mapping = '\\',
--     insert_mappings = false
--   }
--
-- }

